// Name Puzzle Maker: drop-in letter puzzle for "Jiggy"
// Generated by Name Puzzle Maker. Rendered with OpenSCAD 2025.03+ (Manifold backend).
//
// Font: Andika Bold, SIL Open Font License 1.1 (c) SIL International.
// Keep Andika-Bold.ttf in a "fonts" folder next to this file (it is in the
// website's fonts/ folder), or install Andika on your computer.
//
// Base 236.4463 x 99.295 x 8 mm (9.3 x 3.9 in), 1 plate(s) on Bambu A1 (256 x 256 mm).
// The letter positions and base size below were computed for these exact
// settings. Small changes to fit_clearance, thicknesses or chamfers are safe;
// for a different name or letter height, use the website again.

use <fonts/Andika-Bold.ttf>

/* [Output] */
// What to render. Each plate is ready to slice: everything flat at Z = 0.
part = "plate_1"; // [assembled, base, letters, plate_1]
// Letter index for part = "letter" (used by the website).
letter_index = 0;

/* [Fit] */
// Gap per side between letter and pocket: 0.2 snug, 0.3 default, 0.4 loose.
fit_clearance = 2;
// 45 degree chamfer around the top of each pocket, so letters drop in easily.
lead_in = 0.5;
lead_in_steps = 5;

/* [Sizes] */
// Cap height of the capital letters (mm).
letter_height = 63.5;
letter_thickness = 8;
pocket_depth = 5;
// Solid floor under the pockets.
base_floor = 3;
// Vertical corner cut, 45 degrees in plan view.
corner_chamfer = 4;
// Top perimeter edge. Keep below side margin - 0.8 mm (2 - 0.8).
edge_chamfer = 1;
// Bottom perimeter edge, counters elephant's foot.
bottom_chamfer = 0.4;

/* [Letters] */
// 45 degree chamfer around the top face of each letter.
letter_chamfer = 1;
// And around its bottom face (elephant's foot, easier drop-in).
letter_bottom_chamfer = 0.4;
// Chamfer of the letters' vertical corners (plan view). Limited to 3.5% of the cap height,
// because it is cut by eroding and re-growing the outline, which would delete thin strokes.
letter_corner_chamfer = 1;
// Width of the bar that joins the dot of i and j to its stem.
bridge_width = 5;

/* [Hidden] */
base_thickness = pocket_depth + base_floor;
// Pocket openings sit side_margin = 2 mm from the edge of the base's flat top face,
// with at least letter_gap = 3 mm of wall between neighbouring pockets.
base_size = [236.4463, 99.295];
font = "Andika:style=Bold";
// text() size that makes capitals letter_height tall (cap height = 0.99013 x size).
font_size = letter_height / 0.99013;
text_fn = 48;
// Height of one step when a chamfer is cut as a stack of offsets.
chamfer_step = 0.1;
// Cut a little above the top face so pockets never share a face with it
// (also the overlap between stacked chamfer steps).
overcut = 0.01;

letters = [
  ["J", 4.4073, 25.9434],  // [character, pen x, baseline y] in base coordinates
  ["i", 49.2048, 25.9434],
  ["g", 77.0405, 25.9434],
  ["g", 128.5797, 25.9434],
  ["y", 182.1884, 25.9434],
];

// Bridges that join the dot of i and j to the stem, so each letter prints as
// one piece. [x0, y0, x1, y1] in units of font_size give the stem's centre line
// ((x0 + x1) / 2) and the bar's vertical span; the bar is bridge_width wide.
glyph_bridges = [
  ["i", [0.1192, 0.6311, 0.312, 0.8918]],
];

// Build plates: [part, x, y, rotation]; part -1 is the base, otherwise a letter index.
plates = [
  [ // plate 1
    [-1, 9.7769, 114.7769, 0],
    [0, 8.4718, 46.2769, 0],
    [1, 44.3518, 41.9281, 0],
    [2, 66.5311, 64.5439, 0],
    [3, 113.2842, 64.5439, 0],
    [4, 164.8217, 65.4142, 0]
  ],
];

// ---------------------------------------------------------------- modules

// The bar that joins the dot of i / j to its stem, centred on the stem. k cuts its corners at 45 degrees.
module bar(b, k = 0) {
  w = bridge_width;
  h = (b[3] - b[1]) * font_size;
  kk = min(k, h / 2.5);
  translate([(b[0] + b[2]) / 2 * font_size - w / 2, b[1] * font_size])
    if (kk > 0) polygon([[kk, 0], [w - kk, 0], [w, kk], [w, h - kk], [w - kk, h], [kk, h], [0, h - kk], [0, kk]]);
    else square([w, h]);
}

// One letter as a 2D shape, pen origin at [0, 0] on the baseline. The pockets are cut from this
// outline (the layout measures it), and so are the letters, apart from their rounded-off corners.
module glyph(ch) {
  text(ch, size = font_size, font = font, halign = "left", valign = "baseline", $fn = text_fn);
  for (b = [for (e = glyph_bridges) if (e[0] == ch) e[1]]) bar(b);
}

// The letter's own outline: the vertical corners of the letter are chamfered. The bar between a dot
// and its stem is added afterwards (with its own chamfered corners) so the chamfering cannot cut it.
module letter_outline(ch) {
  c = letter_corner_chamfer;
  if (c > 0) offset(delta = c, chamfer = true) offset(delta = -c)
    text(ch, size = font_size, font = font, halign = "left", valign = "baseline", $fn = text_fn);
  else text(ch, size = font_size, font = font, halign = "left", valign = "baseline", $fn = text_fn);
  for (b = [for (e = glyph_bridges) if (e[0] == ch) e[1]]) bar(b, c);
}

// One letter, standing on its bottom face. The full letter outline is kept between the
// chamfers; the pocket is cut from the un-chamfered glyph(), so the letter always fits. Top and bottom faces are chamfered at 45 degrees, cut as stacked
// steps chamfer_step tall (finer than a print layer) from progressively inset outlines.
module letter(i) {
  ch = letters[i][0];
  bot = letter_bottom_chamfer;
  top = letter_chamfer;
  nb = bot > 0 ? max(1, round(bot / chamfer_step)) : 0;
  nt = top > 0 ? max(1, round(top / chamfer_step)) : 0;
  translate([0, 0, bot]) linear_extrude(height = letter_thickness - bot - top) letter_outline(ch);
  if (nb > 0) for (k = [0 : nb - 1])
    translate([0, 0, k * bot / nb])
      linear_extrude(height = bot - k * bot / nb + overcut)
        offset(delta = -(bot - (k + 0.5) * bot / nb)) letter_outline(ch);
  if (nt > 0) for (k = [0 : nt - 1])
    translate([0, 0, letter_thickness - top - overcut])
      linear_extrude(height = top - k * top / nt + overcut)
        offset(delta = -(top - (k + 0.5) * top / nt)) letter_outline(ch);
}

// Plan outline of the base: rectangle with 45 degree corner cuts, shrunk by inset.
function outline(inset) =
  let (w = base_size[0], d = base_size[1], i = inset,
       k = corner_chamfer - inset * (2 - sqrt(2)))
  [[i + k, i], [w - i - k, i], [w - i, i + k], [w - i, d - i - k],
   [w - i - k, d - i], [i + k, d - i], [i, d - i - k], [i, i + k]];

// Base slab with chamfered bottom and top edges, built as a stack of outlines.
module base_body() {
  layers = concat(
    bottom_chamfer > 0 ? [[bottom_chamfer, 0], [0, bottom_chamfer]] : [[0, 0]],
    edge_chamfer > 0 ? [[0, base_thickness - edge_chamfer], [edge_chamfer, base_thickness]]
                     : [[0, base_thickness]]);
  m = len(layers);
  points = [for (l = layers) for (q = outline(l[0])) [q[0], q[1], l[1]]];
  faces = concat(
    [[for (j = [0:7]) j]],
    [for (l = [0:m - 2]) for (j = [0:7]) [l * 8 + j, (l + 1) * 8 + j, (l + 1) * 8 + (j + 1) % 8, l * 8 + (j + 1) % 8]],
    [[for (j = [7:-1:0]) (m - 1) * 8 + j]]);
  polyhedron(points, faces);
}

// Pocket for letter i: the letter outline offset outward by fit_clearance,
// plus a stepped 45 degree lead-in that is fit_clearance + lead_in wide at the top.
module pocket(i) {
  translate([letters[i][1], letters[i][2], base_thickness]) {
    translate([0, 0, -pocket_depth])
      linear_extrude(height = pocket_depth + overcut)
        offset(delta = fit_clearance) glyph(letters[i][0]);
    for (k = [1:lead_in_steps])
      translate([0, 0, -k * lead_in / lead_in_steps])
        linear_extrude(height = k * lead_in / lead_in_steps + overcut)
          offset(delta = fit_clearance + lead_in * (lead_in_steps - k + 1) / lead_in_steps)
            glyph(letters[i][0]);
  }
}

module base() difference() {
  base_body();
  for (i = [0:len(letters) - 1]) pocket(i);
}

module assembled() {
  base();
  for (i = [0:len(letters) - 1])
    translate([letters[i][1], letters[i][2], base_floor]) letter(i);
}

module place(item) translate([item[1], item[2], 0]) rotate([0, 0, item[3]]) children();

module plate(number) {
  for (item = plates[number - 1])
    place(item) if (item[0] < 0) base(); else letter(item[0]);
}

// Every letter in a row, for a quick look.
module letters_row() {
  for (i = [0:len(letters) - 1]) translate([letters[i][1], 0, 0]) letter(i);
}

if (part == "assembled") assembled();
else if (part == "base") base();
else if (part == "letter") letter(letter_index);
else if (part == "letters") letters_row();
else for (number = [1:len(plates)]) if (part == str("plate_", number)) plate(number);
