// Name Puzzle Maker: drop-in letter puzzle for "Ellie"
// Generated by Name Puzzle Maker. Rendered with OpenSCAD 2025.03+ (Manifold backend).
//
// Font: Andika Bold, SIL Open Font License 1.1 (c) SIL International.
// Keep Andika-Bold.ttf in a "fonts" folder next to this file (it is in the
// website's fonts/ folder), or install Andika on your computer.
//
// Base 54.3224 x 24.0543 x 8 mm (2.1 x 0.9 in), 1 plate(s) on Bambu A1 (256 x 256 mm).
// The letter positions and base size below were computed for these exact
// settings. Small changes to fit_clearance, thicknesses or chamfers are safe;
// for a different name or letter height, use the website again.

use <fonts/Andika-Bold.ttf>

/* [Output] */
// What to render. Each plate is ready to slice: everything flat at Z = 0.
part = "plate_1"; // [assembled, base, letters, plate_1]
// Letter index for part = "letter" (used by the website).
letter_index = 0;

/* [Fit] */
// Gap per side between letter and pocket: 0.2 snug, 0.3 default, 0.4 loose.
fit_clearance = 0.3;
// 45 degree chamfer around the top of each pocket, so letters drop in easily.
lead_in = 0.5;
lead_in_steps = 5;

/* [Sizes] */
// Cap height of the capital letters (mm).
letter_height = 14;
letter_thickness = 8;
pocket_depth = 5;
// Solid floor under the pockets.
base_floor = 3;
// Vertical corner cut, 45 degrees in plan view.
corner_chamfer = 4;
// Top perimeter edge. Keep below side margin - 0.8 mm (2 - 0.8).
edge_chamfer = 1;
// Bottom perimeter edge, counters elephant's foot.
bottom_chamfer = 0.4;

/* [Letters] */
// 45 degree chamfer around the top face of each letter.
letter_chamfer = 0.6;
// And around its bottom face (elephant's foot, easier drop-in).
letter_bottom_chamfer = 0.4;
// Width of the bar that joins the dot of i and j to its stem.
bridge_width = 5;

/* [Hidden] */
base_thickness = pocket_depth + base_floor;
// Pocket openings sit side_margin = 2 mm from the edge of the base's flat top face,
// with at least letter_gap = 3 mm of wall between neighbouring pockets.
base_size = [54.3224, 24.0543];
font = "Andika:style=Bold";
// text() size that makes capitals letter_height tall (cap height = 0.99013 x size).
font_size = letter_height / 0.99013;
text_fn = 48;
// Height of one step when a chamfer is cut as a stack of offsets.
chamfer_step = 0.1;
// Cut a little above the top face so pockets never share a face with it
// (also the overlap between stacked chamfer steps).
overcut = 0.01;

letters = [
  ["E", 2.5021, 4.9118],  // [character, pen x, baseline y] in base coordinates
  ["l", 15.9481, 4.9118],
  ["l", 23.5162, 4.9118],
  ["i", 31.984, 4.9118],
  ["e", 40.742, 4.9118],
];

// Bridges that join the dot of i and j to the stem, so each letter prints as
// one piece. [x0, y0, x1, y1] in units of font_size give the stem's centre line
// ((x0 + x1) / 2) and the bar's vertical span; the bar is bridge_width wide.
glyph_bridges = [
  ["i", [0.1192, 0.6311, 0.312, 0.8918]],
];

// Build plates: [part, x, y, rotation]; part -1 is the base, otherwise a letter index.
plates = [
  [ // plate 1
    [-1, 73.7712, 115.9729, 0],
    [0, 131.6552, 126.0271, 0],
    [1, 145.6879, 124.6847, 0],
    [2, 153.7564, 124.6847, 0],
    [3, 162.8111, 125.0683, 0],
    [4, 172.496, 130.0545, 0]
  ],
];

// ---------------------------------------------------------------- modules

// One letter as a 2D shape, pen origin at [0, 0] on the baseline.
module glyph(ch) {
  text(ch, size = font_size, font = font, halign = "left", valign = "baseline", $fn = text_fn);
  for (b = [for (e = glyph_bridges) if (e[0] == ch) e[1]])
    translate([(b[0] + b[2]) / 2 * font_size - bridge_width / 2, b[1] * font_size])
      square([bridge_width, (b[3] - b[1]) * font_size]);
}

// One letter, standing on its bottom face. The full outline is kept between the
// chamfers, so the part that sits in the pocket is exactly the outline the pocket
// was cut from. Top and bottom faces are chamfered at 45 degrees, cut as stacked
// steps chamfer_step tall (finer than a print layer) from progressively inset outlines.
module letter(i) {
  ch = letters[i][0];
  bot = letter_bottom_chamfer;
  top = letter_chamfer;
  nb = bot > 0 ? max(1, round(bot / chamfer_step)) : 0;
  nt = top > 0 ? max(1, round(top / chamfer_step)) : 0;
  translate([0, 0, bot]) linear_extrude(height = letter_thickness - bot - top) glyph(ch);
  if (nb > 0) for (k = [0 : nb - 1])
    translate([0, 0, k * bot / nb])
      linear_extrude(height = bot - k * bot / nb + overcut)
        offset(delta = -(bot - (k + 0.5) * bot / nb)) glyph(ch);
  if (nt > 0) for (k = [0 : nt - 1])
    translate([0, 0, letter_thickness - top - overcut])
      linear_extrude(height = top - k * top / nt + overcut)
        offset(delta = -(top - (k + 0.5) * top / nt)) glyph(ch);
}

// Plan outline of the base: rectangle with 45 degree corner cuts, shrunk by inset.
function outline(inset) =
  let (w = base_size[0], d = base_size[1], i = inset,
       k = corner_chamfer - inset * (2 - sqrt(2)))
  [[i + k, i], [w - i - k, i], [w - i, i + k], [w - i, d - i - k],
   [w - i - k, d - i], [i + k, d - i], [i, d - i - k], [i, i + k]];

// Base slab with chamfered bottom and top edges, built as a stack of outlines.
module base_body() {
  layers = concat(
    bottom_chamfer > 0 ? [[bottom_chamfer, 0], [0, bottom_chamfer]] : [[0, 0]],
    edge_chamfer > 0 ? [[0, base_thickness - edge_chamfer], [edge_chamfer, base_thickness]]
                     : [[0, base_thickness]]);
  m = len(layers);
  points = [for (l = layers) for (q = outline(l[0])) [q[0], q[1], l[1]]];
  faces = concat(
    [[for (j = [0:7]) j]],
    [for (l = [0:m - 2]) for (j = [0:7]) [l * 8 + j, (l + 1) * 8 + j, (l + 1) * 8 + (j + 1) % 8, l * 8 + (j + 1) % 8]],
    [[for (j = [7:-1:0]) (m - 1) * 8 + j]]);
  polyhedron(points, faces);
}

// Pocket for letter i: the letter outline offset outward by fit_clearance,
// plus a stepped 45 degree lead-in that is fit_clearance + lead_in wide at the top.
module pocket(i) {
  translate([letters[i][1], letters[i][2], base_thickness]) {
    translate([0, 0, -pocket_depth])
      linear_extrude(height = pocket_depth + overcut)
        offset(delta = fit_clearance) glyph(letters[i][0]);
    for (k = [1:lead_in_steps])
      translate([0, 0, -k * lead_in / lead_in_steps])
        linear_extrude(height = k * lead_in / lead_in_steps + overcut)
          offset(delta = fit_clearance + lead_in * (lead_in_steps - k + 1) / lead_in_steps)
            glyph(letters[i][0]);
  }
}

module base() difference() {
  base_body();
  for (i = [0:len(letters) - 1]) pocket(i);
}

module assembled() {
  base();
  for (i = [0:len(letters) - 1])
    translate([letters[i][1], letters[i][2], base_floor]) letter(i);
}

module place(item) translate([item[1], item[2], 0]) rotate([0, 0, item[3]]) children();

module plate(number) {
  for (item = plates[number - 1])
    place(item) if (item[0] < 0) base(); else letter(item[0]);
}

// Every letter in a row, for a quick look.
module letters_row() {
  for (i = [0:len(letters) - 1]) translate([letters[i][1], 0, 0]) letter(i);
}

if (part == "assembled") assembled();
else if (part == "base") base();
else if (part == "letter") letter(letter_index);
else if (part == "letters") letters_row();
else for (number = [1:len(plates)]) if (part == str("plate_", number)) plate(number);
