// Name Puzzle Maker: drop-in letter puzzle for "Lily"
// Generated by Name Puzzle Maker. Rendered with OpenSCAD 2025.03+ (Manifold backend).
//
// Font: Andika Bold, SIL Open Font License 1.1 (c) SIL International.
// Keep Andika-Bold.ttf in a "fonts" folder next to this file (it is in the
// website's fonts/ folder), or install Andika on your computer.
//
// Base 183.0142 x 115.6372 x 8 mm (7.2 x 4.6 in), 2 plate(s) on Prusa MK4 (250 x 210 mm).
// The letter positions and base size below were computed for these exact
// settings. Small changes to fit_clearance, thicknesses or chamfers are safe;
// for a different name or letter height, use the website again.

use <fonts/Andika-Bold.ttf>

/* [Output] */
// What to render. Each plate is ready to slice: everything flat at Z = 0.
part = "plate_1"; // [assembled, base, letters, plate_1, plate_2]
// Letter index for part = "letter" (used by the website).
letter_index = 0;

/* [Fit] */
// Gap per side between letter and pocket: 0.2 snug, 0.3 default, 0.4 loose.
fit_clearance = 0.3;
// 45 degree chamfer around the top of each pocket, so letters drop in easily.
lead_in = 0.5;
lead_in_steps = 5;

/* [Sizes] */
// Cap height of the capital letters (mm).
letter_height = 76.2;
letter_thickness = 8;
pocket_depth = 5;
// Solid floor under the pockets.
base_floor = 3;
// Vertical corner cut, 45 degrees in plan view.
corner_chamfer = 4;
// Top perimeter edge. Keep below side margin - 0.8 mm (2 - 0.8).
edge_chamfer = 1;
// Bottom perimeter edge, counters elephant's foot.
bottom_chamfer = 0.4;

/* [Hidden] */
base_thickness = pocket_depth + base_floor;
// Pocket openings sit side_margin = 2 mm from the edge of the base's flat top face,
// with at least letter_gap = 3 mm of wall between neighbouring pockets.
base_size = [183.0142, 115.6372];
font = "Andika:style=Bold";
// text() size that makes capitals letter_height tall (cap height = 0.99013 x size).
font_size = letter_height / 0.99013;
text_fn = 48;
// Cut a little above the top face so pockets never share a face with it.
overcut = 0.01;

letters = [
  ["L", -3.8886, 28.3306],  // [character, pen x, baseline y] in base coordinates
  ["i", 55.0878, 28.3306],
  ["l", 88.4906, 28.3306],
  ["y", 121.8934, 28.3306],
];

// Bridges that join the dot of i and j to the stem, so each letter prints as
// one piece. [x0, y0, x1, y1] in units of font_size; the bridge is exactly as
// wide as the stem.
glyph_bridges = [
  ["i", [0.1192, 0.4919, 0.312, 0.9393]],
];

// Build plates: [part, x, y, rotation]; part -1 is the base, otherwise a letter index.
plates = [
  [ // plate 1
    [-1, 6.5937, 90.3907, 0],
    [0, 186.7787, 129.8279, 0],
    [1, -0.9738, 3.9721, 0]
  ],
  [ // plate 2
    [2, 77.0935, 63.2467, 0],
    [3, 107.6671, 93.518, 0]
  ],
];

// ---------------------------------------------------------------- modules

// One letter as a 2D shape, pen origin at [0, 0] on the baseline.
module glyph(ch) {
  text(ch, size = font_size, font = font, halign = "left", valign = "baseline", $fn = text_fn);
  for (b = [for (e = glyph_bridges) if (e[0] == ch) e[1]])
    translate([b[0], b[1]] * font_size) square([b[2] - b[0], b[3] - b[1]] * font_size);
}

module letter(i) linear_extrude(height = letter_thickness) glyph(letters[i][0]);

// Plan outline of the base: rectangle with 45 degree corner cuts, shrunk by inset.
function outline(inset) =
  let (w = base_size[0], d = base_size[1], i = inset,
       k = corner_chamfer - inset * (2 - sqrt(2)))
  [[i + k, i], [w - i - k, i], [w - i, i + k], [w - i, d - i - k],
   [w - i - k, d - i], [i + k, d - i], [i, d - i - k], [i, i + k]];

// Base slab with chamfered bottom and top edges, built as a stack of outlines.
module base_body() {
  layers = concat(
    bottom_chamfer > 0 ? [[bottom_chamfer, 0], [0, bottom_chamfer]] : [[0, 0]],
    edge_chamfer > 0 ? [[0, base_thickness - edge_chamfer], [edge_chamfer, base_thickness]]
                     : [[0, base_thickness]]);
  m = len(layers);
  points = [for (l = layers) for (q = outline(l[0])) [q[0], q[1], l[1]]];
  faces = concat(
    [[for (j = [0:7]) j]],
    [for (l = [0:m - 2]) for (j = [0:7]) [l * 8 + j, (l + 1) * 8 + j, (l + 1) * 8 + (j + 1) % 8, l * 8 + (j + 1) % 8]],
    [[for (j = [7:-1:0]) (m - 1) * 8 + j]]);
  polyhedron(points, faces);
}

// Pocket for letter i: the letter outline offset outward by fit_clearance,
// plus a stepped 45 degree lead-in that is fit_clearance + lead_in wide at the top.
module pocket(i) {
  translate([letters[i][1], letters[i][2], base_thickness]) {
    translate([0, 0, -pocket_depth])
      linear_extrude(height = pocket_depth + overcut)
        offset(delta = fit_clearance) glyph(letters[i][0]);
    for (k = [1:lead_in_steps])
      translate([0, 0, -k * lead_in / lead_in_steps])
        linear_extrude(height = k * lead_in / lead_in_steps + overcut)
          offset(delta = fit_clearance + lead_in * (lead_in_steps - k + 1) / lead_in_steps)
            glyph(letters[i][0]);
  }
}

module base() difference() {
  base_body();
  for (i = [0:len(letters) - 1]) pocket(i);
}

module assembled() {
  base();
  for (i = [0:len(letters) - 1])
    translate([letters[i][1], letters[i][2], base_floor]) letter(i);
}

module place(item) translate([item[1], item[2], 0]) rotate([0, 0, item[3]]) children();

module plate(number) {
  for (item = plates[number - 1])
    place(item) if (item[0] < 0) base(); else letter(item[0]);
}

// Every letter in a row, for a quick look.
module letters_row() {
  for (i = [0:len(letters) - 1]) translate([letters[i][1], 0, 0]) letter(i);
}

if (part == "assembled") assembled();
else if (part == "base") base();
else if (part == "letter") letter(letter_index);
else if (part == "letters") letters_row();
else for (number = [1:len(plates)]) if (part == str("plate_", number)) plate(number);
